/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./../components/business/account/AccountCard.vue')['default']
    ArticleEditor: typeof import('./../components/business/article/ArticleEditor.vue')['default']
    DistillPanel: typeof import('./../components/business/project/DistillPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./../components/common/ErrorBoundary.vue')['default']
    KeywordDisplay: typeof import('./../components/business/project/KeywordDisplay.vue')['default']
    LoadingButton: typeof import('./../components/common/button/LoadingButton.vue')['default']
    LoadingState: typeof import('./../components/common/LoadingState.vue')['default']
    PlatformIcon: typeof import('./../components/business/account/PlatformIcon.vue')['default']
    PlatformSelector: typeof import('./../components/business/publish/PlatformSelector.vue')['default']
    ProgressCard: typeof import('./../components/business/publish/ProgressCard.vue')['default']
    ProjectManager: typeof import('./../components/business/project/ProjectManager.vue')['default']
    ProjectSidebar: typeof import('./../components/business/project/ProjectSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditor: typeof import('./../components/business/editor/WangEditor.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
